### ISSUE TITLE
Creating Log Groups Failed

### ISSUE THREAD

**Issue by apguerrera** [gilt/s3-sftp-bridge#2]
Looking forward to moving some of my workloads to Lambda but keep getting caught out on the following error. Any ideas?

CREATE_FAILED   AWS::Logs::MetricFilter S3toSFTPMetric  The specified log group does not exist.
CREATE_FAILED   AWS::Logs::MetricFilter SFTPtoS3Metric  The specified log group does not exist.
CREATE_FAILED   AWS::Logs::MetricFilter FunctionTimeoutMetric   The specified log group does not exist.
CREATE_FAILED   AWS::Logs::MetricFilter ErrorMetric The specified log group does not exist.

I've re zipped the repo and uploaded it to my own bucket (As it needed to be in the same region)
Attached is my template file (renamed as .txt so i could upload here). I tried to follow the instructions as best I could. 

Thanks 
Adrian
[s3-sftp-lambda.txt](https://github.com/gilt/s3-sftp-bridge/files/534906/s3-sftp-lambda.txt)

**Comment by bretrbs** [comment]
Errors are visible when using my own region and when using us-east-1. Any ideas?

**Comment by griffrick** [comment]
If you look at the documentation for AWS::Logs::MetricFilter [located here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-metricfilter.html) you'll see that the Log Groups need to already be created. I ended up just creating the Log Groups myself in the same template. I added a new resource:
  "UniversalLoggingGroup": {
      "Type" : "AWS::Logs::LogGroup",
      "Properties" : {
        "RetentionInDays" : 1
      }
    }
